# Configuration file for Dependabot

version: 2

# Define the package manager and its configuration
updates:
  - package-ecosystem: "pip"  # Use pip as the package manager
    directory: "requirements.txt"  # Location of package manifests
    schedule:
      interval: "daily"  # Check for updates daily
      time: "02:00"  # Perform updates at 2 AM UTC
      timezone: "UTC"  # Use the UTC timezone for updates
    labels: "dependencies"  # Optional: add a label to updates
    assignees: ["username"]  # Optional: assign updates to a specific user