# version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python dropship_project/manage.py collectstatic --noinput &&
      python dropship_project/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=yourdomain.com www.yourdomain.com localhost 127.0.0.1 [::1]
    depends_on:
      - db
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=dropship_db
      - POSTGRES_USER=dropship_user
      - POSTGRES_PASSWORD=dropship_password

volumes:
  postgres_data:
