name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ["3.x"]  # Dit zorgt ervoor dat altijd de laatste stabiele Python 3 versie wordt gebruikt.
        ubuntu-version: ["ubuntu-latest"]  # Dit gebruikt altijd de laatste stabiele Ubuntu versie.

    runs-on: ${{ matrix.ubuntu-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ runner.arch }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ runner.arch }}-
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "⚠️ No requirements.txt found, skipping dependencies installation."; fi

      - name: Run Django Migrations
        run: |
          if [ -f manage.py ]; then python manage.py migrate; else echo "⚠️ manage.py not found, skipping migrations."; fi

      - name: Run Tests
        run: |
          if [ -f manage.py ]; then python manage.py test; else echo "⚠️ manage.py not found, skipping tests."; fi

      - name: Check Code Style with Flake8
        run: |
          pip install flake8
          echo "Running Flake8..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      - name: Cleanup Pip Cache
        if: always()
        run: python -m pip cache
