# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow integrates njsscan with GitHub's Code Scanning feature
# nodejsscan is a static security code scanner that finds insecure code patterns in your Node.js applications

name: njsscan SARIF

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '31 0 * * 5' # Runs every Friday at 00:31 UTC

permissions:
  contents: read
  security-events: write

jobs:
  njsscan:
    name: NJSSCAN Code Scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout
      security-events: write # Required for uploading SARIF results
      actions: read # Only required for private repositories

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run njsscan Security Analysis
        id: njsscan
        uses: ajinabraham/njsscan-action@7237412fdd36af517e2745077cedbf9d6900d711
        with:
          args: '. --sarif --output results.sarif || true'

      - name: Upload njsscan Report to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          wait-for-processing: true
