name: OSV-Scanner Workflow

on:
  # Triggers the workflow for pull requests to the main branch
  pull_request:
    branches:
      - main
  # Triggers for merge groups targeting the main branch
  merge_group:
    branches:
      - main
  # Scheduled scan every Saturday at 06:38 UTC
  schedule:
    - cron: '38 6 * * 6'
  # Triggers for pushes to the main branch
  push:
    branches:
      - main

permissions:
  security-events: write
  contents: read

jobs:
  # Scheduled and push scans
  scan-scheduled:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v1
    with:
      scan-args: |
        -r
        --skip-git
        ./

  # Pull request and merge group scans
  scan-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v1
    with:
      scan-args: |
        -r
        --skip-git
        ./
