name: Qodana Code Quality Check

on:
  pull_request:
    branches:
      - main

jobs:
  qodana-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Qodana Cache
      id: cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/qodana
          ./qodana-results
        key: qodana-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          qodana-${{ runner.os }}-

    - name: Run Qodana Scan
      uses: JetBrains/qodana-action@v2024.2
      with:
        project-dir: .
        results-dir: ./qodana-results
        cache-dir: ~/.cache/qodana
        token: ${{ secrets.QODANA_TOKEN }}
        fail-threshold: error # Configure based on your requirement
        upload-result: true

    - name: Upload Qodana Results as Artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: qodana-results
        path: ./qodana-results
